### ISSUE TITLE
TypeError: __html.replace is not a function

### ISSUE THREAD

**Issue by LCHarold** [jonkemp/list-stylesheets#9]
This is the bug report that was requested in the discussion of PR #8.

Get error:
> TypeError: __html.replace is not a function
>     at C:\repo\github\list-stylesheets\node_modules\list-stylesheets\index.js:27:33
>     at Array.forEach (<anonymous>)
>     at encodeCodeBlocks (C:\repo\github\list-stylesheets\node_modules\list-stylesheets\index.js:24:33)
>     at encodeEntities (C:\repo\github\list-stylesheets\node_modules\list-stylesheets\index.js:45:20)
>     at module.exports (C:\repo\github\list-stylesheets\node_modules\list-stylesheets\index.js:52:22)
>     at module.exports (C:\repo\github\list-stylesheets\node_modules\extract-css\index.js:11:16)
>     at C:\repo\github\list-stylesheets\node_modules\inline-css\lib\inlineContent.js:15:9
>     at Promise._execute (C:\repo\github\list-stylesheets\node_modules\bluebird\js\release\debuggability.js:313:9)
>     at Promise._resolveFromExecutor (C:\repo\github\list-stylesheets\node_modules\bluebird\js\release\promise.js:483:18)
>     at new Promise (C:\repo\github\list-stylesheets\node_modules\bluebird\js\release\promise.js:79:10)
>     at inlineContent (C:\repo\github\list-stylesheets\node_modules\inline-css\lib\inlineContent.js:8:12)
>     at C:\repo\github\list-stylesheets\node_modules\inline-css\index.js:31:9
>     at Promise._execute (C:\repo\github\list-stylesheets\node_modules\bluebird\js\release\debuggability.js:313:9)
>     at Promise._resolveFromExecutor (C:\repo\github\list-stylesheets\node_modules\bluebird\js\release\promise.js:483:18)
>     at new Promise (C:\repo\github\list-stylesheets\node_modules\bluebird\js\release\promise.js:79:10)
>     at module.exports (C:\repo\github\list-stylesheets\node_modules\inline-css\index.js:8:12)

I added code to reproduce this in my fork at https://github.com/LCHarold/list-stylesheets. To reproduce, clone my repo then do `npm run coverage` which will run and then invoke "postcoverage" which in turn calls ./setup/process-coverage-report.js, which is where the error above happens.

You can then demonstrate that explicitly converting _html to String resolves the issue by adding the code in PR #8 to the dependencies with:
`"list-stylesheets": "github:LCHarold/list-stylesheets#master"`
and then do `npm run coverage` again.

**Comment by jonkemp** [comment]
Update inline-css to 2.4.1 and the issue should be resolved. The string conversion was made in the parent module so all the downstream modules should get it. This is the same fix that was done in the gulp plugin.

**Comment by LCHarold** [comment]
Confirmed... the error goes away now with inline-css 2.4.1.
